import "./style-v3.css";
import {W,H,MARK,HEADER_BYTES,crc32,r32,concat,pageCapacity,makeHeader,readMeta,drawPage,imageFromFile,readPacket,marker,modeLabel,type ModeCode} from "./codec-v4";

const app=document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML=`<main><header><div class="brand-row"><div class="pv-logo" aria-hidden="true"></div><div><p class="eyebrow">PAPER STORAGE EXPERIMENT</p><h1>PaperVault <span>α</span></h1><p class="lead">ファイルを白黒セルへ変換し、紙から復元する実験用Webアプリ。</p><span class="logo-note">四隅マーカーと共通の PaperVault シグネット</span></div></div></header><section class="notice"><strong>α版の制約</strong><span>原寸・正対・余白を切らないスキャン向け。多値グレースケール方式は容量が増えますが、印刷・スキャン品質の影響を強く受けます。</span></section><nav class="tabs"><button class="tab active" data-tab="encode">保存する</button><button class="tab" data-tab="decode">復元する</button><button class="tab" data-tab="calibrate">印刷テスト</button></nav><section id="encode" class="panel active"><h2>ファイルを紙面化</h2><label class="drop"><input id="fileInput" type="file"><span>ファイルを選択</span><small>元ファイル名・拡張子・MIMEタイプも保存します</small></label><div class="controls"><label>セルサイズ<select id="cellSize"><option value="12">Safe（約1.02 mm）</option><option value="10" selected>Normal（約0.85 mm）</option><option value="8">Dense（約0.68 mm）</option><option value="6">Experimental（約0.51 mm）</option><option value="5">Ultra（約0.42 mm）</option><option value="4">Maximum（約0.34 mm）</option></select></label><label>反復回数<select id="repeat"><option value="1">1×（容量優先）</option><option value="3" selected>3×（標準）</option><option value="5">5×（耐久優先）</option></select></label><label>記録方式<select id="modeSelect"><option value="0" selected>Standard 1-bit monochrome</option><option value="1">Experimental 2-bit grayscale（約2倍）</option><option value="2">Experimental 3-bit grayscale（約3倍）</option><option value="3">Experimental 4-bit grayscale（約4倍）</option></select></label></div><div id="capacityInfo" class="status"></div><div id="modeNote" class="experimental-note"></div><button id="encodeBtn" class="primary" disabled>ページを生成</button><div id="encodeStatus" class="status"></div><div id="pages" class="pages"></div></section><section id="decode" class="panel"><h2>画像から復元</h2><label class="drop"><input id="scanInput" type="file" accept="image/png,image/jpeg,image/webp" multiple><span>スキャン画像を選択</span><small>復元後は元のファイル名と拡張子で保存されます</small></label><button id="decodeBtn" class="primary" disabled>復元を開始</button><div id="decodeStatus" class="status"></div></section><section id="calibrate" class="panel"><h2>印刷テスト</h2><p>2bit・3bit・4bitグレースケールの階調分離も確認できます。</p><button id="calibrateBtn" class="primary">テストシート生成</button><div id="calibrateStatus" class="status"></div><div id="calibration"></div></section><footer>PaperVault v0.2.1-alpha · <a href="https://github.com/sakusdev" target="_blank" rel="noreferrer">@sakusdev</a> · local-first</footer></main>`;

const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
document.querySelectorAll<HTMLButtonElement>(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===t));document.querySelectorAll(".panel").forEach(p=>p.classList.toggle("active",p.id===t.dataset.tab));});
const fileInput=$("#fileInput") as HTMLInputElement,scanInput=$("#scanInput") as HTMLInputElement,encodeBtn=$("#encodeBtn") as HTMLButtonElement,decodeBtn=$("#decodeBtn") as HTMLButtonElement,cellSelect=$("#cellSize") as HTMLSelectElement,repeatSelect=$("#repeat") as HTMLSelectElement,modeSelect=$("#modeSelect") as HTMLSelectElement;
fileInput.onchange=()=>encodeBtn.disabled=!fileInput.files?.length;scanInput.onchange=()=>decodeBtn.disabled=!scanInput.files?.length;
const currentMode=()=>Number(modeSelect.value) as ModeCode;
function updateCapacity(){const mode=currentMode(),cap=pageCapacity(Number(cellSelect.value),Number(repeatSelect.value),mode);$("#capacityInfo").textContent=`推定容量: 約 ${cap.toLocaleString()} bytes / A4片面`;$("#modeNote").textContent=mode===0?"Standard 1-bit monochrome: 最も安定する基本方式です。":mode===1?"2-bit grayscale: 4階調。比較的現実的な容量増加モードです。":mode===2?"3-bit grayscale: 8階調。約3倍ですが、階調の潰れにかなり弱い実験モードです。":"4-bit grayscale: 16階調。理論上約4倍ですが、一般的な印刷・スキャンでは復元困難な可能性が高い限界実験モードです。"}
cellSelect.onchange=repeatSelect.onchange=modeSelect.onchange=updateCapacity;updateCapacity();
function downloadCanvas(canvas:HTMLCanvasElement,name:string){canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)},"image/png")}
function cardFor(canvas:HTMLCanvasElement,name:string){const card=document.createElement("article");card.className="page-card";const actions=document.createElement("div");actions.className="actions";const dl=document.createElement("button");dl.textContent="PNGを保存";dl.onclick=()=>downloadCanvas(canvas,name);const pr=document.createElement("button");pr.textContent="このページを印刷";pr.onclick=()=>{document.querySelectorAll(".print-target").forEach(x=>x.classList.remove("print-target"));card.classList.add("print-target");window.print()};actions.append(dl,pr);card.append(canvas,actions);return card}
encodeBtn.onclick=async()=>{const file=fileInput.files![0],cell=Number(cellSelect.value),repeat=Number(repeatSelect.value),mode=currentMode(),status=$("#encodeStatus"),pages=$("#pages");pages.innerHTML="";const raw=new Uint8Array(await file.arrayBuffer()),cap=pageCapacity(cell,repeat,mode);if(cap<=0)throw new Error("容量設定が不正です");const total=Math.ceil(raw.length/cap),fileId=crypto.getRandomValues(new Uint32Array(1))[0];status.textContent=`${file.name}\n${raw.length.toLocaleString()} bytes → ${total}ページ（約${cap.toLocaleString()} bytes/ページ, ${modeLabel(mode)}）`;for(let p=0;p<total;p++){const payload=raw.slice(p*cap,Math.min(raw.length,(p+1)*cap)),packet=concat(makeHeader(file,fileId,p,total,raw.length,payload,cell,repeat,mode),payload),canvas=drawPage(packet,cell,repeat,`${file.name} PAGE ${p+1}/${total}`,mode);pages.append(cardFor(canvas,`papervault-${String(p+1).padStart(4,"0")}.png`));await new Promise(r=>setTimeout(r,0))}};
decodeBtn.onclick=async()=>{const status=$("#decodeStatus");status.textContent="読み取り中…";try{const found=new Map<number,Uint8Array>();let total=0,totalBytes=0,fileId:number|undefined,name="restored.bin",mime="application/octet-stream",mode:ModeCode=0;for(const f of Array.from(scanInput.files!)){const bytes=readPacket(await imageFromFile(f)),id=r32(bytes,8),page=r32(bytes,12),meta=readMeta(bytes);total=r32(bytes,16);totalBytes=r32(bytes,20);name=meta.name;mime=meta.mime;mode=meta.mode;const len=r32(bytes,24),expected=r32(bytes,28),payload=bytes.slice(HEADER_BYTES,HEADER_BYTES+len);if(crc32(payload)!==expected)throw new Error(`${f.name}: CRC不一致`);if(fileId!==undefined&&fileId!==id)throw new Error("異なるファイルのページが混ざっています");fileId=id;found.set(page,payload)}if(found.size!==total)throw new Error(`ページ不足: ${found.size}/${total}`);const ordered:Uint8Array[]=[];for(let i=0;i<total;i++){const p=found.get(i);if(!p)throw new Error(`ページ${i+1}がありません`);ordered.push(p)}const restored=concat(...ordered).slice(0,totalBytes),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([restored],{type:mime}));a.download=name;a.click();status.textContent=`復元成功: ${name} (${restored.length.toLocaleString()} bytes)\n方式: ${modeLabel(mode)}`}catch(e){status.textContent=`復元失敗: ${e instanceof Error?e.message:String(e)}`}};
function drawStrip(ctx:CanvasRenderingContext2D,y:number,bits:number){const n=1<<bits,w=Math.max(12,Math.floor(1800/n));ctx.fillStyle="#000";ctx.font="bold 18px sans-serif";ctx.fillText(`${bits}-bit grayscale (${n} levels)`,110,y+22);for(let i=0;i<n;i++){const g=Math.round(255*(1-i/(n-1)));ctx.fillStyle=`rgb(${g},${g},${g})`;ctx.fillRect(360+i*w,y,w,34);ctx.strokeStyle="#777";ctx.strokeRect(360+i*w,y,w,34)}}
$("#calibrateBtn").onclick=()=>{const holder=$("#calibration");holder.innerHTML="";const c=document.createElement("canvas");c.width=W;c.height=H;const ctx=c.getContext("2d",{alpha:false})!;ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);marker(ctx,10,10,MARK);marker(ctx,W-80,10,MARK);marker(ctx,10,H-80,MARK);marker(ctx,W-80,H-80,MARK);ctx.fillStyle="#000";ctx.font="bold 42px sans-serif";ctx.fillText("PaperVault / print calibration",110,90);let y=150;for(const cell of [16,14,12,10,8,6,5,4]){ctx.font="bold 27px sans-serif";ctx.fillStyle="#000";ctx.fillText(`${cell}px @300dpi ≈ ${(cell/300*25.4).toFixed(2)} mm`,110,y);y+=22;const cols=Math.floor((W-220)/cell),rows=Math.floor(115/cell);let seed=cell*9973;const rnd=()=>((seed=(seed*1664525+1013904223)>>>0)&1);for(let r=0;r<rows;r++)for(let col=0;col<cols;col++)if(rnd())ctx.fillRect(110+col*cell,y+r*cell,cell,cell);y+=rows*cell+20;drawStrip(ctx,y,2);y+=48;drawStrip(ctx,y,3);y+=48;drawStrip(ctx,y,4);y+=70}holder.append(cardFor(c,"papervault-print-calibration.png"));$("#calibrateStatus").textContent="A4・100%・片面で印刷し、余白を切らずにスキャンしてください。各階調が別々に見えるか確認してください。"};
