export const W=2480,H=3508,MARGIN=80,DATA_TOP=170,HEADER_BYTES=192,MARK=70;
export const MAGIC=new TextEncoder().encode("PVLT");
export type ModeCode=0|1|2|3;
const enc=new TextEncoder(),dec=new TextDecoder();
const bitsPerCell=(m:ModeCode)=>m===0?1:m===1?2:m===2?3:4;
const levels=(m:ModeCode)=>1<<bitsPerCell(m);
export function crc32(bytes:Uint8Array){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^(0xedb88320&-(c&1));}return(c^0xffffffff)>>>0}
export function u32(out:Uint8Array,at:number,value:number){new DataView(out.buffer).setUint32(at,value>>>0,false)}
export function r32(bytes:Uint8Array,at:number){return new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(at,false)}
export function concat(...parts:Uint8Array[]){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let at=0;for(const p of parts){out.set(p,at);at+=p.length}return out}
export function pageCapacity(cell:number,repeat:number,mode:ModeCode){const cols=Math.floor((W-2*MARGIN)/cell),rows=Math.floor((H-DATA_TOP-MARGIN)/cell);return Math.max(0,Math.floor(cols*rows*bitsPerCell(mode)/(8*repeat))-HEADER_BYTES)}
export function marker(ctx:CanvasRenderingContext2D,x:number,y:number,s:number){ctx.fillStyle="#000";ctx.fillRect(x,y,s,s);ctx.fillStyle="#fff";ctx.fillRect(x+s*.2,y+s*.2,s*.6,s*.6);ctx.beginPath();ctx.moveTo(x+s*.5,y+s*.32);ctx.lineTo(x+s*.68,y+s*.5);ctx.lineTo(x+s*.5,y+s*.68);ctx.lineTo(x+s*.32,y+s*.5);ctx.closePath();ctx.fillStyle="#000";ctx.fill();ctx.fillStyle="#fff";ctx.fillRect(x+s*.47,y+s*.37,s*.06,s*.26);ctx.fillRect(x+s*.41,y+s*.43,s*.18,s*.06)}
export function makeHeader(file:File,fileId:number,page:number,total:number,totalBytes:number,payload:Uint8Array,cell:number,repeat:number,mode:ModeCode){const h=new Uint8Array(HEADER_BYTES),name=enc.encode(file.name).slice(0,96),mime=enc.encode(file.type||"application/octet-stream").slice(0,48);h.set(MAGIC,0);h[4]=4;h[5]=cell;h[6]=repeat;h[7]=name.length;u32(h,8,fileId);u32(h,12,page);u32(h,16,total);u32(h,20,totalBytes);u32(h,24,payload.length);u32(h,28,crc32(payload));h[32]=mime.length;h[33]=mode;h.set(name,40);h.set(mime,136);return h}
export function readMeta(bytes:Uint8Array){return{version:bytes[4]||1,mode:(bytes[33]||0) as ModeCode,name:dec.decode(bytes.slice(40,40+bytes[7]))||"restored.bin",mime:dec.decode(bytes.slice(136,136+bytes[32]))||"application/octet-stream"}}
function bytesToSymbols(bytes:Uint8Array,repeat:number,mode:ModeCode){const bpc=bitsPerCell(mode),count=Math.ceil(bytes.length*8/bpc),out=new Uint8Array(count*repeat);let bitPos=0,at=0;for(let i=0;i<count;i++){let v=0;for(let k=0;k<bpc;k++){v<<=1;if(bitPos<bytes.length*8){const bi=Math.floor(bitPos/8),shift=7-(bitPos%8);v|=(bytes[bi]>>shift)&1}bitPos++}for(let r=0;r<repeat;r++)out[at++]=v}return out}
function symbolsToBytes(symbols:Uint8Array,repeat:number,byteCount:number,mode:ModeCode){const bpc=bitsPerCell(mode),count=Math.ceil(byteCount*8/bpc),out=new Uint8Array(byteCount);let at=0,bitPos=0;for(let i=0;i<count;i++){let sum=0;for(let r=0;r<repeat;r++)sum+=symbols[at++]||0;const v=Math.max(0,Math.min(levels(mode)-1,Math.round(sum/repeat)));for(let k=bpc-1;k>=0;k--){if(bitPos<byteCount*8){const bi=Math.floor(bitPos/8),shift=7-(bitPos%8);out[bi]|=((v>>k)&1)<<shift}bitPos++}}return out}
function grayForSymbol(v:number,mode:ModeCode){const max=levels(mode)-1;return Math.round(255*(1-v/max))}
function quantizeGray(avg:number,mode:ModeCode){const max=levels(mode)-1;return Math.max(0,Math.min(max,Math.round((255-avg)*max/255)))}
export function modeLabel(mode:ModeCode){return mode===0?"STD 1-bit monochrome":mode===1?"EXP 2-bit grayscale":mode===2?"EXP 3-bit grayscale":"EXP 4-bit grayscale"}
export function drawPage(packet:Uint8Array,cell:number,repeat:number,label:string,mode:ModeCode){const canvas=document.createElement("canvas");canvas.width=W;canvas.height=H;const ctx=canvas.getContext("2d",{alpha:false})!;ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);marker(ctx,10,10,MARK);marker(ctx,W-10-MARK,10,MARK);marker(ctx,10,H-10-MARK,MARK);marker(ctx,W-10-MARK,H-10-MARK,MARK);ctx.fillStyle="#000";ctx.font="bold 30px sans-serif";ctx.fillText("PaperVault",MARGIN,72);ctx.font="20px monospace";ctx.fillText(label,MARGIN,104);ctx.font="bold 15px sans-serif";ctx.fillText(modeLabel(mode),MARGIN,132);const symbols=bytesToSymbols(packet,repeat,mode);let i=0,y=DATA_TOP;while(i<symbols.length&&y+cell<=H-MARGIN){for(let x=MARGIN;x+cell<=W-MARGIN&&i<symbols.length;x+=cell,i++){const gray=grayForSymbol(symbols[i],mode);if(gray<255){ctx.fillStyle=`rgb(${gray},${gray},${gray})`;ctx.fillRect(x,y,cell,cell)}}y+=cell}return canvas}
export async function imageFromFile(file:File){const bmp=await createImageBitmap(file),c=document.createElement("canvas");c.width=W;c.height=H;const ctx=c.getContext("2d",{alpha:false})!;ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.drawImage(bmp,0,0,W,H);bmp.close();return c}
export function readPacket(canvas:HTMLCanvasElement){const ctx=canvas.getContext("2d")!;for(const cell of [12,10,8,6,5,4])for(const repeat of [1,3,5])for(const mode of [0,1,2,3] as ModeCode[]){const byteCap=pageCapacity(cell,repeat,mode)+HEADER_BYTES,bpc=bitsPerCell(mode),symbolCount=Math.ceil(byteCap*8/bpc)*repeat,symbols=new Uint8Array(symbolCount);let i=0,y=DATA_TOP;while(i<symbolCount&&y+cell<=H-MARGIN){for(let x=MARGIN;x+cell<=W-MARGIN&&i<symbolCount;x+=cell,i++){const d=ctx.getImageData(Math.floor(x+cell/2),Math.floor(y+cell/2),1,1).data,avg=(d[0]+d[1]+d[2])/3;symbols[i]=quantizeGray(avg,mode)}y+=cell}const bytes=symbolsToBytes(symbols,repeat,byteCap,mode);if(bytes.slice(0,4).every((v,k)=>v===MAGIC[k])&&bytes[5]===cell&&bytes[6]===repeat&&((bytes[33]||0) as ModeCode)===mode)return bytes}throw new Error("PaperVaultヘッダーを検出できません。余白・向き・原寸を確認してください。")}
